name: rmu_space
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  dio: ">=2.1.13 <6.0.0"
  http: any
  path_provider: ^0.5.0+1
  flutter_local_notifications: ^0.8.4
  flutter_launcher_icons: ^0.7.0

  chewie: ^0.9.8+1
  video_player: ^0.10.2+1
  rflutter_alert: ^1.0.3
  dart_random_choice: ^0.0.2
  expandable: ^3.0.0+1
  smooth_star_rating: ^1.0.3
  shared_preferences: ^0.5.3+4
  intl: ^0.16.0


  neeko: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_app.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/icon_app.png
    - assets/icons/icon_splash.png
    - assets/icons/icon_opacity.png

    #icon home
    - assets/images/test.png
    - assets/images/video.png


  fonts:
    - family: Kanit
      fonts:
       - asset: assets/fonts/Kanit-Black.ttf
       - asset: assets/fonts/Kanit-BlackItalic.ttf
       - asset: assets/fonts/Kanit-Bold.ttf
       - asset: assets/fonts/Kanit-BoldItalic.ttf
       - asset: assets/fonts/Kanit-Italic.ttf
       - asset: assets/fonts/Kanit-Light.ttf
       - asset: assets/fonts/Kanit-Medium.ttf
       - asset: assets/fonts/Kanit-Regular.ttf
       - asset: assets/fonts/Kanit-Thin.ttf
